name: hrk_logging
description: >-
  A library for beginners to quickly add colors and emojis to logs
repository: https://github.com/hrishikesh-kadam/hrk_logging.dart
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
