name: hrk_logging
version: 0.1.1

description: >-
  A library for beginners to quickly add colors and emojis to logs
repository: https://github.com/hrishikesh-kadam/hrk_logging.dart
screenshots:
  - description: 'Terminal Screenshot'
    path: screenshots/terminal_screenshot.png
  - description: 'Web Console Screenshot'
    path: screenshots/web_console_screenshot.png
topics:
  - logging
  - logger
  - logs
  - log

environment:
  sdk: ^3.0.0

dependencies:
  hrk_batteries: ^0.1.0
  logging: ^1.1.0

dev_dependencies:
  hrk_analysis: ^0.1.0
  test: ^1.21.0
