name: hrk_logging
description: Colorful logs by HRK
repository: https://github.com/hrishikesh-kadam/hrk_logging.dart
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
